// app/blog/page.tsx
import { groupBy } from "../../utils/group-by"
import { getSortedBlogData } from "../../utils/getMarkdown"
import Link from "next/link"
import styles from "./page.module.css"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Blog",
}

export default function BlogPage() {
  const allPosts = getSortedBlogData()
  const groupedPosts = Object.entries(
    groupBy(allPosts, post => new Date(post.date).getFullYear().toString()),
  ).reverse()

  return (
    <div className={styles.list}>
      <h1 className={styles.title}>Blog</h1>
      <p>
        Sharing my thoughts on frontend development, life, and anything in
        between. Writing mostly for my past self. Thanks for stopping by!
      </p>

      {groupedPosts.map(([year, posts]) => (
        <section key={year}>
          <h2 className={styles.groupTitle}>{year}</h2>
          <div className={styles.groupPosts}>
            {posts
              .sort(
                (pA, pB) =>
                  new Date(pB.date).getTime() - new Date(pA.date).getTime(),
              )
              .map(post => (
                <div className={styles.groupPost} key={post.id}>
                  <Link
                    href={`/blog/${encodeURIComponent(post.id)}`}
                    className={styles.postLink}
                  >
                    {post.title}
                  </Link>
                </div>
              ))}
          </div>
        </section>
      ))}
    </div>
  )
}

// src/routes/blog/+page.svelte
<script>
	import { groupBy } from '$lib/utils/group-by';

	export let data;

	let groupedPosts = Object.entries(
		groupBy(data.posts, (post) => new Date(post.meta.date).getFullYear().toString())
	).reverse();
</script>

<svelte:head>
	<title>Blog | Ondrej Sevcik</title>
</svelte:head>

<div class="list">
	{#each groupedPosts as [year, posts]}
		<section>
			<h2 class="groupTitle">{year}</h2>
			<div class="groupPosts">
				{#each posts as post}
					<div class="groupPost">
						<a href={post.path} class="postLink">{post.meta.title}</a>
					</div>
				{/each}
			</div>
		</section>
	{/each}
</div>

<style>
	.list {
		max-width: 36rem;
		display: flex;
		flex-direction: column;
		gap: 2rem;
		margin-left: auto;
		margin-right: auto;
	}

	.postLink {
		font-size: var(--step-0);
		line-height: 1.5;
		font-weight: 500;
		color: var(--blue-800);
	}

	.postLink:hover {
		text-decoration: underline;
	}

	.groupPosts {
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		gap: 1rem;
	}

	.groupPost {
		display: flex;
		flex-direction: column;
	}

	.groupTitle {
		font-weight: 700;
		font-size: var(--step-1);
		line-height: 4rem;
	}
</style>
